name: Build

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.x]
        runtime:
          - osx-arm64
          - osx-x64
          - linux-x64
          - win-x64

        include:
          - runtime: osx-arm64
            os: macOS-latest

          - runtime: osx-x64
            os: macOS-latest

          - runtime: linux-x64
            os: ubuntu-latest

          - runtime: win-x64
            os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install libarchive-tools
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt update; sudo apt -y install libarchive-tools build-essential;
        sudo apt install -y libx11-dev libxtst-dev libxss-dev libpng-dev libjpeg-dev snapd;
        sudo snap install snapcraft --classic;
        echo "Version Number ${{ toJson(job) }} ${{ toJson(needs) }}";

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
    - run: npm install
    
    - name: Get Version Number
      id: getPackageInfo
      uses: jaywcjlove/github-action-package@main
      with:
        path: ./package.json

    - name: Build with Node.js
      run: npm run build

    - name: Build with electron-builder arm64
      if: contains(matrix.runtime, 'arm64')
      run: npx electron-builder --arm64 --publish never

    - name: Build with electron-builder x64
      if: contains(matrix.runtime, 'x64')
      run: npx electron-builder --x64 --publish never

    - name: ls Build File
      if: startsWith(matrix.os, 'windows') == false
      run: echo -e "\n构建目录内容如下:"; ls -la dist/

    - name: ls Build File windows
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win')
      run: |
        Write-Host "`n构建目录内容如下:" -ForegroundColor Green
        Get-ChildItem -Path "dist\" -Force

    - name: Upload .dmg arm64 Artifact
      uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'macos') && startsWith(matrix.runtime, 'osx-arm64')
      with:
        name: lol_wom_helper-${{ steps.getPackageInfo.outputs.version }}-nightly-mac-arm64.dmg
        path: dist/lol_wom_helper-${{ steps.getPackageInfo.outputs.version }}.dmg

    - name: Upload .dmg x64 Artifact
      uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'macos') && startsWith(matrix.runtime, 'osx-x64')
      with:
        name: lol_wom_helper-${{ steps.getPackageInfo.outputs.version }}-nightly-mac-x64.dmg
        path: dist/lol_wom_helper-${{ steps.getPackageInfo.outputs.version }}.dmg

    - name: Upload .AppImage x64 Artifact
      uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.runtime, 'linux-x64')
      with:
        name: lol_wom_helper-${{ steps.getPackageInfo.outputs.version }}-nightly-amd64.AppImage
        path: dist/lol_wom_helper-${{ steps.getPackageInfo.outputs.version }}.AppImage

    - name: Upload .deb amd x64 Artifact
      uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.runtime, 'linux-x64')
      with:
        name: lol_wom_helper-${{ steps.getPackageInfo.outputs.version }}-nightly_amd64.snap
        path: dist/lol_wom_helper_${{ steps.getPackageInfo.outputs.version }}_amd64.snap

    - name: Upload .exe x64 Artifact
      uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
      with:
        name: lol_wom_helper-${{ steps.getPackageInfo.outputs.version }}-nightly_x64-Setup.exe
        path: dist/lol_wom_helper-${{ steps.getPackageInfo.outputs.version }}-setup.exe
